name: Secure Pass CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🧪 Run Basic Test
        run: echo "No tests configured"

      - name: 🐳 Build Docker Image
        run: docker build -t secure-pass .

      - name: 🚀 Run Docker Container
        run: docker run -d -p 8080:80 secure-pass
